participant Sue
participant Server
participant Jim
state over Server: 3
parallel{
Server->Sue: Update
Server->Jim: Update
note right of Jim: svn update
note left of Sue: svn up 
}
parallel{
state over Jim: work
state over Sue: work
note right of Jim: vim sharedfile.py
note left of Sue: nano sharedfile.py
}
parallel{
note right of Jim: svn commit
Jim->Server: Commit
}
state over Server: 4
parallel{
Sue-->Server: Failed commit
note left of Sue
	svn commit
	! svn: out of date: 'sharedfile.py'
end note
}
parallel{
Server->Sue: Update
note left of Sue: svn up
}
parallel{
note left of Sue: nano sharedfile.py
state over Sue: Resolve conflicts
}
parallel{
Sue->Server: Commit
note left of Sue: svn ci
}
state over Server: 5