participant Sue
participant Server
participant Jim
state over Server: 1
parallel{
Server->Jim : Checkout
note right of Jim: svn checkout http://ucl.ac.uk/ourcode
}
parallel{
Server->Sue: Checkout
note left of Sue: svn co http://ucl.ac.uk/ourcode
}
parallel{
state over Jim: work
note right of Jim: nano jimfile.py
}
parallel{
Jim->Server: Commit
note right of Jim: svn commit
}
state over Server: 2
parallel {
note left of Sue: svn update
Server->Sue: Update
}
parallel{
note left of Sue
	cat jimfile.py
	notepad++ suefile.py
end note
state over Sue: work
}
parallel{
note left of Sue: svn commit
Sue->Server: Commit
}
state over Server: 3