participant Jim as J
participant "Jim's repo" as Jr
participant Origin as O
participant "Sue's repo" as Sr
participant Sue as S

parallel{
state over J: work
note left of J
test
end note
}

parallel{
note left of J
	git init
	git add mycode
	git commit
end note
J->Jr: init
}

parallel{
note left of J
	git remote add 
	--track master origin
	git@github.com:ucl/foo.git
end note 
O-->Jr: track
}
parallel{
	Jr->O: push
	note left of J: git push
}

parallel{
note right of S: git clone git@github.com:ucl/foo.git
O->Sr: clone
Sr->S: clone
}
state over S: work
parallel{
note right of S: git commit -a
S->Sr: commit
}
parallel{
Sr->O: push
note right of S: git push
}
parallel{
O->Jr: fetch
note left of J: git fetch
}
parallel{
Jr->J: merge
note left of J: git merge
}
state over J: work
parallel{
note left of J: git commit -a
J->Jr: commit
}
parallel{
note left of J: git push
Jr->O: push
}
parallel{
O->Sr: pull
Sr->S: pull
note right of S: git pull
}



