Working Directory -> Staging Area : git add
Staging Area -> Local Repository : git commit
Working Directory -> Local Repository : git commit -a
Staging Area -> Working Directory : git checkout
Local Repository -> Staging Area : git reset
Local Repository -> Working Directory : git checkout HEAD
parallel {
Local Repository -> Staging Area: git reset --hard
Staging Area -> Working Directory: git reset --hard
}